from fastapi import Depends, Request, HTTPException, APIRouter, Response, Cookie
import os
from sqlalchemy.sql import text
from sqlalchemy.orm import Session
from src.config.db import get_db_names, default_engine, get_tenant_db
from src.authorization.utils import  get_current_user_with_refresh
# from src.masters.schemas import MenuResponse
from src.masters.models import WarehouseMst
from src.masters.query import  get_warehouse_list, get_branch_list
from datetime import datetime

router = APIRouter()

@router.get("/get_warehouse_table")
async def get_warehouse(
    request: Request,
    response: Response,
    db: Session = Depends(get_tenant_db),
    token_data: dict = Depends(get_current_user_with_refresh),
    search: str = None
):
    try:
        co_id = request.query_params.get("co_id")
        # incoming param is 'branches' e.g. '1,2' per API client
        branches_param = request.query_params.get("branches") or request.query_params.get("branch_ids")
        if not co_id:
            raise HTTPException(status_code=400, detail="Company ID (co_id) is required")
        # Prepare search parameter for LIKE if provided
        search_param = f"%{search}%" if search else None
        # parse branches CSV into list of ints
        branch_ids_list = None
        if branches_param:
            try:
                branch_ids_list = [int(x.strip()) for x in str(branches_param).split(",") if x.strip()]
            except Exception:
                raise HTTPException(status_code=400, detail="Invalid branches parameter")

        warehousequery = get_warehouse_list(branch_ids_list if branch_ids_list is not None else [])
        result = db.execute(warehousequery, {"co_id": int(co_id), "search": search_param, "branch_ids": branch_ids_list}).fetchall()
        warehouse = [dict(row._mapping) for row in result]
        branchquery = get_branch_list()
        branch_result = db.execute(branchquery).fetchall()
        branches = [dict(row._mapping) for row in branch_result]
        return {"data": warehouse, "branches": branches}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/warehouse_create")
async def warehouse_create(
    request: Request,
    response: Response,
    db: Session = Depends(get_tenant_db),
    token_data: dict = Depends(get_current_user_with_refresh),
):
    try:
        payload = await request.json()
        co_id_query = request.query_params.get("co_id")
        co_id = payload.get("co_id") if payload.get("co_id") is not None else co_id_query
        if co_id is None:
            raise HTTPException(status_code=400, detail="Company ID (co_id) is required")

        # derive updated_by from token
        updated_by = None
        if token_data and token_data.get("user_id"):
            try:
                updated_by = int(token_data.get("user_id"))
            except Exception:
                updated_by = None

        # parse inputs
        try:
            branch_id = int(payload.get("branch_id")) if payload.get("branch_id") is not None else None
        except Exception:
            raise HTTPException(status_code=400, detail="Invalid branch_id")

        warehouse_name = payload.get("warehouse_name")
        parent_warehouse_id = payload.get("parent_warehouse_id")
        if parent_warehouse_id is not None:
            try:
                parent_warehouse_id = int(parent_warehouse_id)
            except Exception:
                parent_warehouse_id = None

        warehouse_type = payload.get("warehouse_type")

        # create model instance
        wh = WarehouseMst(
            warehouse_name=warehouse_name,
            branch_id=branch_id,
            parent_warehouse_id=parent_warehouse_id,
            warehouse_type=warehouse_type,
            updated_by=updated_by,
        )

        db.add(wh)
        db.commit()
        # refresh to get autogenerated id
        db.refresh(wh)

        return {"message": "Warehouse created successfully", "warehouse_id": getattr(wh, 'warehouse_id', None)}
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    